### ISSUE TITLE
use a globbing library

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components-codemods#2]
> styled-components-codemods v4 src/**/*.js (this will only work if your terminal expands globs)

We should just bring in a globbing lib and do it no matter what the terminal is. Need to make sure the separators are right for win vs *nix

**Comment by mxstbr** [comment]
Yeah for sure

**Comment by probablyup** [comment]
5fbd74fd92ee7dca27a83ddf6064fb1593473c22
