### ISSUE TITLE
Difficult to know progress, or if finished

### ISSUE THREAD

**Issue by vegarsti** [styled-components/styled-components-codemods#7]
I'm migrating to v4 and running this mod on a pretty large directory at once. So will probably take some time. I just want to be sure that it's still running, it just says 

```
npx: installed 356 in 8.264s
```

**Comment by mxstbr** [comment]
Hmm no it should log something out and be ~relatively quick. On our ~100k LoC codebase it took a couple seconds, so it's probably not working?

**Comment by vegarsti** [comment]
It finished after a while, but just silently, and it doesn't appear to have worked. If I want to use it on a directory, is it correct to do this? That's what I did, at least.

```
npx styled-components-codemods v4-injectGlobalToCreateGlobalStyle .
```

**Comment by mxstbr** [comment]
No, you have to specify a glob like so:

```sh
npx styled-components-codemods v4-injectGlobalToCreateGlobalStyle './**/*.js'
```
